FROM python:3.11-slim

WORKDIR /tests

# ---------------- Dependencias del sistema ----------------
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    build-essential \
    bash \
    curl \
    && rm -rf /var/lib/apt/lists/*

# ---------------- Dependencias de Python ----------------
RUN pip install --no-cache-dir requests psycopg2-binary pytest locust

# ---------------- Copiar tests y script ----------------
COPY smoke /tests/smoke
COPY baseline /tests/baseline
COPY locust /tests/locust
COPY locust/users.json /tests/locust/users.json
COPY run_tests.sh /tests/run_tests.sh
RUN chmod +x /tests/run_tests.sh

# Crear carpeta de reports
RUN mkdir -p /tests/reports

# ---------------- Variables de entorno ----------------
ENV CMS_API_URL=http://cms-backend:8000
ENV LOCUST_USERS=50
ENV LOCUST_SPAWN_RATE=5
ENV LOCUST_RUNTIME=2m

# ---------------- Comando por defecto ----------------
CMD ["/tests/run_tests.sh"]
